type Todo {
  id: ID!
  text: String!
  done: Boolean!
}

input TodoInput {
  id: ID!
  text: String!
  done: Boolean!
}

type Mutation {
  createTodo(text: String!): Todo!
  updateTodo(input: TodoInput!): Todo!
  deleteTodo(todoId: ID!): Todo!
}

type Query {
  getTodos: [Todo!]!
  getTodo(todoId: ID!): Todo!
}